use phpcourier;

DROP TABLE IF EXISTS Domains;
DROP TABLE IF EXISTS DomainAccess;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Mail;
DROP TABLE IF EXISTS Aliases;
DROP TABLE IF EXISTS UpdateTime;
DROP TABLE IF EXISTS Sessions;

